hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path('users/',include('users.urls')),

    # path("users/", include("users.urls"))
]

urls.py
from django.contrib import admin
from django.urls import path, include
from hw_project.quotes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path('users/', include('users.urls')),
    path('author/<str:author_id>/', views.author_detail, name='author_detail'),

    # path("users/", include("users.urls"))
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views

from .views import RegisterView, ResetPasswordView

app_name = "users"



urlpatterns = [
    path('registration/', RegisterView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name="logout
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.forms import ModelForm, ImageField, CharField, TextInput, EmailField, EmailInput, PasswordInput

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class RegisterForm(UserCreationForm):
    username = CharField(max_length=16, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    first_name = CharField(max_length=25, widget=TextInput(attrs={'class': 'form-control'}))
    last_name = CharField(max_length=25, widget=TextInput(attrs={'class': 'form-control'}))
    email = EmailField(max_length=30, required=True, widget=EmailInput(attrs={'class': 'form-control'}))
    password1 = CharField(max_length=12, min_length=6, required=True,
                          widget=PasswordInput(attrs={'class': 'form-control'}))
    password2 = CharField(max_length=12, min_length=6, required=True,
                          widget=PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = CharField(max_length=16, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(max_length=12, min_length=8, required=True,
                         widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "password")

users/views.py
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth import login, logout, authenticate
from .forms import RegisterForm, LoginForm
from django.contrib.auth.decorators import login_required


class RegisterView(View):
    template_name = 'users/registration.html'
    form_class = RegisterForm

    # def dispatch(self, request, *args, **kwargs):
    #     if request.user.is_authenticated:
    #         return redirect(to="quotes:root")
    #     return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            user = form.save()
            login(request, user)
            return redirect('quotes:root')  # Перенаправлення на головну сторінку з цитатами після успішної реєстрації

        return render(request, self.template_name, {'form': form})


class CustomLogoutView(View):
    @login_required
    def get(self, request):
        logout(request)
        return redirect('quotes:root')


class LoginView(View):
    template_name = 'users/login.html'
    form_class = LoginForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('quotes:root')  # Перенаправление на главную страницу после успешного логина
            else:
                form.add_error(None, 'Неверные учетные данные. Пожалуйста, попробуйте еще раз.')

        return render(request, self.template_name, {'form': form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'
#
# def get_success_url(self):
#     # Возвращает URL-шаблон, на который нужно перенаправить пользователя после успешного логина
#     return reverse(
#         'quotes:root')  # Здесь 'quotes:root' - это имя URL-шаблона, на который нужно перенаправить пользователя

users/templates/users/login.html
<!-- login.html -->

{% extends "quotes/base.html" %}

{% block content %}

<div class="container">
    <h2 class="mb-3">Login User</h2>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }} </span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>

        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Send</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
        <div class="small text-center">
            <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
        </div>

    </form>

</div>

{% endblock %}

users/templates/users/logout.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="container">
    <h2 class="mb-3">Повертайтесь будь ласка</h2>
</div>

{% endblock %}

users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        Reset password
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

users/templates/users/registration.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="container">
    <h2>Registration User</h2>
    {% if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">First name
                {{ form.first_name }}
            </label>
            <span>{{form.errors.first_name}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Last name
                {{ form.last_name }}
            </label>
            <span>{{form.errors.last_name}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Email
                {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Repeat Password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Send</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>

</div>

{% endblock %}