hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path('users/',include('users.urls')),

    # path("users/", include("users.urls"))
]

quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main, name="root"),
    path('paginate/<int:page>/', views.main, name="root_paginate"),
    # path('', include('users.urls')),
    path('author/<str:id>/', views.author_detail, name='author_detail'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('add_author/', views.add_author, name='add_author'),
    path('first_page/', views.first_page, name='first_page'),
    path('last_page/', views.last_page, name='last_page'),

]

urls.py
from django.contrib import admin
from django.urls import path, include
from hw_project.quotes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path('users/', include('users.urls')),
    path('author/<str:author_id>/', views.author_detail, name='author_detail'),

    # path("users/", include("users.urls"))
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views

from .views import RegisterView, ResetPasswordView

app_name = "users"



urlpatterns = [
    path('registration/', RegisterView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name="logout
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/models.py
from django.db import models


# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    date_born = models.CharField(max_length=50)
    location_born = models.CharField(max_length=150)
    bio = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelMultipleChoiceField, SelectMultiple,ModelChoiceField,Select
from .models import Quote, Author, Tag


class QuoteForm(ModelForm):
    quote = CharField(min_length=5, required=True, widget=TextInput())
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('name'), required=True, widget=SelectMultiple())
    author = ModelChoiceField(queryset=Author.objects.all().order_by('fullname'), widget=Select())

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']
        # exclude = ['tags']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, widget=TextInput())
    date_born = CharField(max_length=50, widget=TextInput)
    location_born = CharField(max_length=150, widget=TextInput())
    bio = CharField(widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'date_born', 'location_born', 'bio']


class TagForm(ModelForm):
    name = CharField(max_length=30, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']

quotes/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from .forms import QuoteForm, AuthorForm, TagForm
from .models import Author, Quote
from .utils import get_mongodb
from bson.objectid import ObjectId


def main(request, page=1):
    # db = get_mongodb()
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)

    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})


def author_detail(request, id):
    author = get_object_or_404(Author, pk=id)
    return render(request, 'quotes/author_detail.html', {'author': author})


# def author_about(request, _id):
#     print(_id)
#     author = Author.objects.get(pk=_id)
#
#     return render(request, 'quotes:author_detail.html', context={'author': author})


def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/add_quote.html', context={'form': QuoteForm(), 'message': 'Form not valid'})

    return render(request, 'quotes/add_quote.html', context={'form': QuoteForm()})


def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to='quotes:root')
    else:
        form = AuthorForm()
    return render(request, 'quotes/add_author.html', {'form': form})


def first_page(request):
    return redirect('quotes:root_paginate', page=1)

def last_page(request):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(quotes, per_page)
    last_page_number = paginator.num_pages
    return redirect('quotes:root_paginate', page=last_page_number)

quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_author' %}">
    {% csrf_token %}
    <div>
        <label> Fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div>
        <label> Born Date:
            {{ form.date_born }}
        </label>
        <span>{{ form.errors.date_born }}</span>
    </div>
    <div>
        <label> Born Location:
            {{ form.location_born }}
        </label>
        <span>{{ form.errors.location_born }}</span>
    </div>
    <div>
        <label> Description:
            {{ form.bio }}
        </label>
        <span>{{ form.errors.bio }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    <div>
        <label> Author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div>
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="...">
        <label> Tags:
            {{ form.tags }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/templates/quotes/author_detail.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>

    <p>
        <strong>Born</strong><span class="author-born-date">{{author.date_born}}</span>
        <span class="author-born-location">{{author.location_born}}</span>
    </p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.bio}}
    </div>
</div>

{% endblock %}

quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>
<body>

<div class="container">
    <div class="row header-box">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>

        </div>

        <div class="col-md-4  sr-5">
            <p>
                {% if user.is_authenticated %}
                <a href="{% url 'users:logout' %}">LogOut</a>
                <a href="{% url 'quotes:add_quote' %}">Add Quote</a>
                <a href="{% url 'quotes:add_author' %}">Add Author</a>
                <a href="{% url 'users:logout' %}">Add Tag</a>
                {% else %}
                <a href="{% url 'users:signup' %}">SignUp</a>
                <a href="{% url 'users:login' %}">Login</a>
                {% endif %}
            </p>
        </div>
    </div>

    {% block content %}
    {% endblock %}

</div>

</body>
</html>

quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}



{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}


        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author}}</small>
        <a href="/author/{{quote.author.id}}">(about)</a>
        </span>
            <div class="tags">
                Tags:

                {% for tag in quote.tags.all %}

                <a class="tag" href="/tag/{{tag.name}}">{{tag}}</a>

                {% endfor %}

            </div>
        </div>

        {% endfor %}
        <nav>
            <ul class="pager">

                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>


                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        >Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>

</div>

{% endblock %}